name: Deploy

on: [push]

jobs:
    deploy:
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                  version: 10
                  run_install: false
            - uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'
                  cache: 'pnpm'
            - run: pnpm install
            - run: pnpm build
            - name: Deploy
              run: |
                cp 404.html dist/404.html
                cd dist
                touch .nojekyll
                git init
                git config user.name 'github-actions[bot]'
                git config user.email 'github-actions[bot]@users.noreply.github.com'
                git checkout -b gh-pages
                git add -A
                git commit -m 'deploy'
                git push -f https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git gh-pages
